// services/notesService.js

/**
 * Notes Service
 *
 * Contains all database query functions for the notes table.
 * This file is the only place in the app that talks to the database directly.
 *
 * Keeping queries here means:
 * - Routes stay clean and only handle req/res logic
 * - Database logic is easy to find and update in one place
 * - Query functions can be reused across multiple routes if needed
 */

import pool from "../db.js"

/**
 * Fetch all notes from the database, newest first.
 *
 * Returns an array of note objects:
 *   [{ id: 1, text: "my note" }, { id: 2, text: "another note" }]
 *
 * Returns an empty array if no notes exist:
 *   []
 */
export async function getAllNotes() {
  const result = await pool.query("SELECT * FROM notes ORDER BY id DESC");
  return result.rows;
}

/**
 * Insert a new note into the database and return it.
 *
 * RETURNING * tells PostgreSQL to send back the full inserted row,
 * including the id that was generated by SERIAL.
 *
 * Returns the newly created note object:
 *   { id: 3, text: "my new note" }
 */
export async function addNote(text) {
  const result = await pool.query(
    "INSERT INTO notes (text) VALUES ($1) RETURNING *",
    [text]
  );
  return result.rows[0];
}

/**
 * Test the database connection by running a minimal query.
 *
 * SELECT 1 is the simplest valid SQL query — it just asks PostgreSQL
 * to return the number 1. If PostgreSQL responds, the connection works.
 *
 * Used by server.js on startup to confirm the database is reachable
 * before any requests come in.
 */
export async function testConnection() {
  await pool.query("SELECT 1");
}